---
pipeline:
    name: genmap
    description: "run the genmap utility to create a genome mappability profile"
    version: v0.0.1
actions: 
    do:
        order: 1
        description: "create a genome mappability profile for a combination of kmer-length and n-errors"
        condaFamilies: 
            - base
            - snakemake
            - genmap        
        optionFamilies: 
            - snakemake        
            - genmap        
        resources:
            required:
                total-ram: 32G
            recommended: 
                n-cpu: 8
                ram-per-cpu: 4G
        job-manager:
            recommended:
                time-limit: 12:00:00
condaFamilies:
    genmap:
        dependencies:
            - genmap=1.3.0        
optionFamilies:
    output:
        options:
            output-dir:
                description: "must be set as --genomes-dir/genmap" 
            data-name:
                description: "must be set as UCSC format genome identifier, e.g., hg38"   
    genmap:
        options:
            kmer-length: 
                order: 1
                short: k
                type: integer
                required: false
                default: 100
                description: "kmer (i.e., read) length used to calculate mappability"
            n-errors: 
                order: 2
                short: e
                type: integer
                required: false
                default: 1
                description: "number of errors (i.e., read mismatches) used to calculate mappability"
container:
    supported: true        # set to true if you maintain a container registry for this pipeline [false]
    registry:  ghcr.io     # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
    owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
    installer: apt-get     # the installer program used by the container OS, typically apt-get or yum [apt-get]
